---
# handlers file for first_role
- block:
   - name: Create fs xfs
     filesystem:
       dev: /dev/mapper/vg_apps-lv_apps
       fstype: xfs
     notify: "Create apps dir"
   - name: "Create apps dir"
     file:
       path: /apps
       state : directory
     notify: "Mount apps"
   - name : "Mount apps"
     mount:
       fstype: xfs
       path: /apps
       src: /dev/mapper/vg_apps-lv_apps
       state: mounted
  when: ansible_os_family == 'RedHat'
- block:
   - name: Create fs ext4 50MB
     filesystem:
       dev: /dev/mapper/vg_application-lv_application
       fstype: ext4
     notify: "Create application dir"
   - name: "Create application dir"
     file:
       path: /application
       state : directory
     notify: "Mount application"
   - name : "Mount application"
     mount:
       fstype: ext4
       path: /application
       src: /dev/mapper/vg_application-lv_application
       state: mounted
  when: ansible_os_family == 'Debian'
